# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.2 on Wed Jul 28 03:57:54 2021
#

import wx




class _175646223_wxFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        kwds["style"] = kwds.get("style", 0)
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((714, 565))
        self.SetTitle("frame")
        self.SetBackgroundColour(wx.Colour(0, 0, 0))

        self.panel_1 = wx.Panel(self, -1, style=wx.BORDER_SIMPLE)
        self.panel_1.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.panel_1.SetForegroundColour(wx.Colour(255, 255, 255))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.backpanel = wx.Notebook(self.panel_1, -1, style=wx.NB_FIXEDWIDTH | wx.NB_FLAT | wx.NB_LEFT)
        self.backpanel.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.backpanel.SetForegroundColour(wx.Colour(255, 255, 255))
        self.backpanel.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_1.Add(self.backpanel, 13, wx.EXPAND, 0)

        self.watchlist = wx.ScrolledWindow(self.backpanel, -1, style=wx.TAB_TRAVERSAL)
        self.watchlist.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.watchlist.SetForegroundColour(wx.Colour(255, 255, 255))
        self.watchlist.SetScrollRate(10, 10)
        self.backpanel.AddPage(self.watchlist, "     Watchlist     ")

        self.Settings = wx.ScrolledWindow(self.backpanel, -1, style=wx.BORDER_NONE | wx.TAB_TRAVERSAL)
        self.Settings.SetScrollRate(7, 7)
        self.backpanel.AddPage(self.Settings, "     Settings     ")

        sizer_3 = wx.BoxSizer(wx.VERTICAL)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.Settings, -1, "Time Frame")
        label_1.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_1.SetForegroundColour(wx.Colour(255, 255, 255))
        label_1.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_4.Add(label_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_1 = wx.TextCtrl(self.Settings, -1, "")
        self.text_ctrl_1.SetMinSize((222, 33))
        sizer_4.Add(self.text_ctrl_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_1 = wx.StaticLine(self.Settings, -1)
        sizer_3.Add(static_line_1, 0, wx.EXPAND, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_5, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.Settings, -1, "EMA 1")
        label_2.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_2.SetForegroundColour(wx.Colour(255, 255, 255))
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_5.Add(label_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_2 = wx.TextCtrl(self.Settings, -1, "")
        self.text_ctrl_2.SetMinSize((222, 33))
        sizer_5.Add(self.text_ctrl_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_2 = wx.StaticLine(self.Settings, -1)
        sizer_3.Add(static_line_2, 0, wx.EXPAND, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.Settings, -1, "EMA 2")
        label_3.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_3.SetForegroundColour(wx.Colour(255, 255, 255))
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_6.Add(label_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_3 = wx.TextCtrl(self.Settings, -1, "")
        self.text_ctrl_3.SetMinSize((222, 33))
        sizer_6.Add(self.text_ctrl_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_3 = wx.StaticLine(self.Settings, -1)
        sizer_3.Add(static_line_3, 0, wx.EXPAND, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_7, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.Settings, -1, "Leverage")
        label_4.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_4.SetForegroundColour(wx.Colour(255, 255, 255))
        label_4.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_7.Add(label_4, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_4 = wx.TextCtrl(self.Settings, -1, "")
        self.text_ctrl_4.SetMinSize((222, 33))
        sizer_7.Add(self.text_ctrl_4, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_4 = wx.StaticLine(self.Settings, -1)
        sizer_3.Add(static_line_4, 0, wx.EXPAND, 0)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_8, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.Settings, -1, "Profit %")
        label_5.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_5.SetForegroundColour(wx.Colour(255, 255, 255))
        label_5.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_8.Add(label_5, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_5 = wx.TextCtrl(self.Settings, -1, "")
        self.text_ctrl_5.SetMinSize((222, 33))
        sizer_8.Add(self.text_ctrl_5, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_5 = wx.StaticLine(self.Settings, -1)
        sizer_3.Add(static_line_5, 0, wx.EXPAND, 0)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_9, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.Settings, -1, "Margin Type")
        label_6.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_6.SetForegroundColour(wx.Colour(255, 255, 255))
        label_6.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_9.Add(label_6, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_6 = wx.TextCtrl(self.Settings, -1, "")
        self.text_ctrl_6.SetMinSize((222, 33))
        sizer_9.Add(self.text_ctrl_6, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_6 = wx.StaticLine(self.Settings, -1)
        sizer_3.Add(static_line_6, 0, wx.EXPAND, 0)

        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_10, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.Settings, -1, "Exit Switch")
        label_7.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_7.SetForegroundColour(wx.Colour(255, 255, 255))
        label_7.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_10.Add(label_7, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.button_2 = wx.ToggleButton(self.Settings, -1, "button_2")
        self.button_2.SetMinSize((222, 44))
        sizer_10.Add(self.button_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_7 = wx.StaticLine(self.Settings, -1)
        sizer_3.Add(static_line_7, 0, wx.EXPAND, 0)

        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_11, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.Settings, -1, "Long Switch")
        label_8.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_8.SetForegroundColour(wx.Colour(255, 255, 255))
        label_8.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_11.Add(label_8, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.button_3 = wx.ToggleButton(self.Settings, -1, "button_3")
        self.button_3.SetMinSize((222, 44))
        sizer_11.Add(self.button_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_8 = wx.StaticLine(self.Settings, -1)
        sizer_3.Add(static_line_8, 0, wx.EXPAND, 0)

        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(sizer_12, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.Settings, -1, "Short Switch")
        label_9.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_9.SetForegroundColour(wx.Colour(255, 255, 255))
        label_9.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_12.Add(label_9, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.button_4 = wx.ToggleButton(self.Settings, -1, "button_4")
        self.button_4.SetMinSize((222, 44))
        sizer_12.Add(self.button_4, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        self.credentials = wx.Panel(self.backpanel, -1)
        self.credentials.Hide()
        self.backpanel.AddPage(self.credentials, "     Credentials     ")

        sizer_13 = wx.BoxSizer(wx.VERTICAL)

        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(sizer_14, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.credentials, -1, "Webhook URL")
        label_10.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_10.SetForegroundColour(wx.Colour(255, 255, 255))
        label_10.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_14.Add(label_10, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_7 = wx.TextCtrl(self.credentials, -1, "")
        self.text_ctrl_7.SetMinSize((222, 33))
        sizer_14.Add(self.text_ctrl_7, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_9 = wx.StaticLine(self.credentials, -1)
        sizer_13.Add(static_line_9, 0, wx.EXPAND, 0)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(sizer_15, 1, wx.EXPAND, 0)

        label_11 = wx.StaticText(self.credentials, -1, "API Key")
        label_11.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_11.SetForegroundColour(wx.Colour(255, 255, 255))
        label_11.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_15.Add(label_11, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_8 = wx.TextCtrl(self.credentials, -1, "")
        self.text_ctrl_8.SetMinSize((222, 33))
        sizer_15.Add(self.text_ctrl_8, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_10 = wx.StaticLine(self.credentials, -1)
        sizer_13.Add(static_line_10, 0, wx.EXPAND, 0)

        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(sizer_16, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.credentials, -1, "API Secret")
        label_12.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_12.SetForegroundColour(wx.Colour(255, 255, 255))
        label_12.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_16.Add(label_12, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_9 = wx.TextCtrl(self.credentials, -1, "")
        self.text_ctrl_9.SetMinSize((222, 33))
        sizer_16.Add(self.text_ctrl_9, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        static_line_11 = wx.StaticLine(self.credentials, -1)
        sizer_13.Add(static_line_11, 0, wx.EXPAND, 0)

        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13.Add(sizer_17, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.credentials, -1, "TLD")
        label_13.SetBackgroundColour(wx.Colour(0, 0, 0))
        label_13.SetForegroundColour(wx.Colour(255, 255, 255))
        label_13.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_17.Add(label_13, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 117)

        self.text_ctrl_10 = wx.TextCtrl(self.credentials, -1, "")
        self.text_ctrl_10.SetMinSize((222, 33))
        sizer_17.Add(self.text_ctrl_10, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 117)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_2.Add((20, 25), 4, wx.EXPAND, 0)

        self.button_1 = wx.Button(self.panel_1, -1, "button_1", style=wx.BORDER_NONE)
        self.button_1.SetMinSize((48, 30))
        sizer_2.Add(self.button_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 13)

        self.credentials.SetSizer(sizer_13)

        self.Settings.SetSizer(sizer_3)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

